### ISSUE TITLE
Main site shows mixed content over HTTPS

### ISSUE THREAD

**Issue by karthickumar42** [bitcoin-solutions/multibit-website#146]
secure site include mixed content in https://multibit.org/

1. Go to https://multibit.org/ in google chrome browser

2. Right click mouse and choose inspect element options

3. click console window u can able to see insecure content css

[blocked] The page at 'https://multibit.org/' was loaded over HTTPS, but ran insecure content from 'http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css': this content should also be loaded over HTTPS.

**Comment by gary-rowe** [comment]
Since the MultiBit Classic site will be retired in favour of the replacement currently on https://beta.multibit.org I've been doing some checking to verify the HTTPS integrity there.

I used [Why No Padlock](https://www.whynopadlock.com/check.php) which gives the following result:

* multibit.org FAIL (for reasons provided in this issue and a bunch of others)
* beta.multibit.org PASS (everything is served over HTTPS correctly)

Based on these results, I'm marking this as awaiting issue which can be cleared when the beta site replaces the main one.

**Comment by gary-rowe** [comment]
Now that the live site has been updated and checked so this can be closed.
