### ISSUE TITLE
Ensure (at least) binaries are mirrored

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-website#154]
We would have more download capacity and resilience if (at least) the MBHD binaries were mirrored across both the hamburg and zebra servers

**Comment by jim618** [comment]
I think the way to do this with our current certificate is:

+ set up all the download links to point to https://www.multibit.org/releases/somewhere-or-other
+ set up DNS so that www.multibit.org points to our current spare server zebra

This way we use the domain name www.multibit.org (which is in our current EV SSL cert, along with beta.multibit.org) purely as a 'download mule'. Everything else we use the hamburg server (domain name: multibit.org)

At some point we can swop the zebra server with something with a faster network card and then remap the DNS for www.multibit.org to the new faster server and retire zebra.

**Comment by jim618** [comment]
Also the www.multibit.org server should redirect anything other than downloads to multibit.org so that if a user types in 
https://www.multibit.org/index.html 
or whatever it'll still work

**Comment by jim618** [comment]
As we have dropped the additional server I will close this as we don't have a host currently to mirror onto,
