### ISSUE TITLE
On Windows 8 test machine, multibit.org and beta.multibit.org not showing in IE 10

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#204]
On the little test box we have, multbit.org and beta.multibit.org are not displaying on the IE 10 browser. IT looks like they are just down. But it shows perfectly fine in Chrome, with the EV signatures showing properly.

**Comment by gary-rowe** [comment]
Our security is too high :-)

There is a lot more information in [this Wikipedia article](http://en.wikipedia.org/wiki/Transport_Layer_Security). In summary:

* IE 11 should be fine
* IE 9-10 will connect if the user enables TLS 1.1, 1.2 with Tools | Internet Options | Advanced (not a hope of that happening IRL)

Can you verify that TLS 1.0 is enabled as a fallback on the server?

**Comment by gary-rowe** [comment]
Further digging [reveals a Microsoft KB issue](https://support.microsoft.com/en-us/kb/2851628) indicating that this is due to a conflict between SSL2.0 and TLS1.2. This means that there is nothing we can do to mitigate it without seriously compromising our security.

[According to browser trends for Jan 2015](http://www.sitepoint.com/browser-trends-january-2015-ie8-usage-triples/) IE < 11 accounts for about 5% of worldwide web traffic. Anyone using this browser will be encountering this kind of problem on secure sites everywhere and will hopefully have taken steps to fix the problem at their end.

As a result I'm marking this as ready for review and close.

**Comment by jim618** [comment]
Fair enough.
Let's not compromise our security for older versions of IE.

Closing.
