### ISSUE TITLE
The GPG signatures aren't easy to access on beta.multibit.org

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#211]
There is nowhere in the text that points to the GPG sigs

**Comment by gary-rowe** [comment]
I've added the signature information to the downloads page. Our research on the number of signature verifications indicates that giving it front page prominence puts it too high in the mix. Consequently the links and explanation are on the downloads page where more technically-minded users will find them.

Also positioning them in this manner simplifies ongoing maintenance.

Standard JS view:
![screen shot 2015-06-08 at 14 07 44](https://cloud.githubusercontent.com/assets/342133/8035379/f8e6d4d8-0de7-11e5-873e-8cd915f70c67.png)

NoScript view:
![screen shot 2015-06-08 at 13 20 29](https://cloud.githubusercontent.com/assets/342133/8035380/facc154c-0de7-11e5-825c-0e7e5facbf93.png)

Ready for review and close.

**Comment by jim618** [comment]
How do the users get hold of the ACTUAL signatures for a particular version ?
(this is what tripped up the OP)

**Comment by jim618** [comment]
oh sorry - I see the main text - I'll check it properly in a bit

**Comment by MrSkinny** [comment]
From the screenshots, it's not clear what happens when you click the links. Right now, when you click the links, it just goes to the release notes further down the page. I looked at the 032b918f8752da5c1aaf9a649e5793255cc6f667 commit and it looks like the links are now going to point directly to a specific directory with the binary download and detached sig?

Assuming that's the case, my .02 is that makes sense! :)

**Comment by gary-rowe** [comment]
Yes, you'll click the section header links and they'll take you to the directory containing the installers and signatures for all variants. You can test it out by clicking the 0.0.8beta on the current version of the site (see https://beta.multibit.org/download.html)

**Comment by MrSkinny** [comment]
Oh I see. From a UX perspective, I wasn't following that the section headers were clickable. I thought the instruction being added: "The section link leads to the installers" actually meant the bullet list of links that immediately follows would take you to the directory. Most users won't read that little line of text anyway. It's not immediately intuitive to me that a panel header styled that way is a link somewhere useful.

I'd actually recommend a "Get Installers and Signatures" link goes into the content area immediately beneath the panel header, one line above "detailed issues on Github".

**Comment by gary-rowe** [comment]
OK, that's useful feedback. It could benefit from being clearer. I'll make the changes tomorrow.

**Comment by gary-rowe** [comment]
Provided additional installation (and integration with mobile) guide section to assist people having problems otherwise they'd be clicking through the help:
![screen shot 2015-06-09 at 12 28 55](https://cloud.githubusercontent.com/assets/342133/8056760/34b4e994-0ea3-11e5-9965-cfd6c8d843d3.png)

Each release section now has its own dedicated "Installers and signatures" link (where appropriate):
![screen shot 2015-06-09 at 12 29 10](https://cloud.githubusercontent.com/assets/342133/8056761/360ac5d4-0ea3-11e5-9279-1ebc35a402bd.png)

Ready for review and close.

**Comment by jim618** [comment]
Checked updated website. Looks clearer and checked links to mobile recommendations. Closing
