### ISSUE TITLE
Importing an offline wallet / private key into MultiBit

### ISSUE THREAD

**Issue by Douglas1949** [bitcoin-solutions/multibit-website#243]
I'm afraid your explanation is not clear to me;  you state:
"1. Create a new wallet saved to a file, say, example.wallet.  2.Export the private keys, WITHOUT A PASSWORD, to a file example.key."
How do you "export the private key" from a paper wallet?   I could understand the instruction if it was "import the private key".

Could you please clarify?  To help you clarify, allow me to state my specific problem - I have bitcoin in a paper wallet (address generated from www.bitaddress.org) - how do I get those BTC into my MultiBit wallet?

Many thanks
Douglas

**Comment by gary-rowe** [comment]
Overall you would be safer importing this into, say, Blockchain.info and then immediately spending into an address created by [MultiBit HD](https://multibit.org).

If you really want to do this [Issue 645 in MultiBit Classic](https://github.com/bitcoin-solutions/multibit/issues/645) covers the problems with importing from paper wallets.

**Working directly with private keys requires extra security precautions - make sure you're offline**

In short, we don't directly support it. You would have to manually construct a WIF format key (begins with K or L) from that provided by BitAddress (you can you use their JavaScript to generate it through their Wallet Details section). Again make sure you're offline when doing this since eavesdroppers are everywhere.

Use the unencrypted file format described in [Exporting Private Keys](https://multibit.org/en/help/v0.5/help_exportingPrivateKeys.html) and make sure that you use a timestamp early enough to cover when the paper wallet was created.

**Comment by Douglas1949** [comment]
Many thanks Gary - much appreciated.
Douglas
