### ISSUE TITLE
Unable to get bitcoin

### ISSUE THREAD

**Issue by Cubittstalkartt** [bitcoin-solutions/multibit-website#272]
The answer above suggests you have a person to send you bitcoin. I have no contact but wish to buy bitcoin. No-one seems to answer.

**Comment by gary-rowe** [comment]
This is the website issue system for textual content of the website. If you'd like to purchase bitcoin you will need to contact an exchange. If you are in Europe, [Bitstamp](https://bitstamp.net) has a good reputation. In the US you may want to consider [Glidera](https://www.glidera.io?r=multibit.org).

Since there is nothing to do here, I'll close this issue.

**Comment by Cubittstalkartt** [comment]
Thank you for the help.
