### ISSUE TITLE
Copying multibit.properties requires finding it first

### ISSUE THREAD

**Issue by sgeffner** [bitcoin-solutions/multibit-website#281]
So in the article on creating multibit wallet on a USB drive,on a Mac, it would help to know where to find Multibit.properties

**Comment by gary-rowe** [comment]
According to the help article (see https://multibit.org/en/help/v0.5/help_runFromUSBDrive.html) you only need to make an empty file called `multibit.properties` in the same directory as MultiBit Classic to trigger the "USB mode".

That said, we have dropped support for USB in MultiBit HD because it is too unreliable. Please read the notes here: https://multibit.org/en/help/hd0.2/backups.html (end of the article).

I'm going to add those notes to the Classic article to discourage people from doing this.

**Comment by gary-rowe** [comment]
Ready for review and close.
