### ISSUE TITLE
changing private note after requesting a new address

### ISSUE THREAD

**Issue by ebonit** [bitcoin-solutions/multibit-website#283]
Hi, not realy a bug but something I think could be better. 

When I add a request, I receive a bitcoin address from my trezor. Then I can add a private note and click save. After that I cannot change the private note. And if i forget the private note, there is no way to add one. I don't know if that is a trezor thing but it would be great if this was possible.

**Comment by gary-rowe** [comment]
Thanks for the feedback. This issue database is for problems with the website itself rather than MultiBit HD. 

There is an issue outstanding for this already (see [#694](https://github.com/bitcoin-solutions/multibit-hd/issues/694)) so I'll close this one here as a duplicate.

It's scheduled for the 0.2.1 release milestone.

Closing.
